sudo: false

language: python

python:
  - "3.5"
  - "3.6"

env:
  - DJANGO="Django>=1.11,<2.0"

cache:
  directories:
  - $HOME/.cache/pip/wheels

install:
  - nvm install 7
  - pip install -U pip wheel setuptools flake8 isort unify
  - pip install $DJANGO -e .[tests]
  - pip freeze

script:
  - python runtests.py
#  - cd js_client && npm install --progress=false && npm test && cd ..
  - flake8
  - isort --check-only --recursive channels
  - unify --check-only --recursive --quote \" channels
